name: Tests
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          lein: 'latest'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run tests"
        run: lein kaocha
